export const BRANDS = [
  {
    id: 1,
    name: 'NovaStar',
    slug: 'novastar',
    logo: '/images/brands/novastar.png',
    description: 'NovaStar là nhà sản xuất hàng đầu thế giới về bộ điều khiển màn hình LED và giải pháp video processing.',
    category: 'Controller',
    website: 'https://www.novastar.tech',
    products: [1, 2],
  },
  {
    id: 2,
    name: 'BOE MLED',
    slug: 'boe-mled',
    logo: '/images/brands/boe.png',
    description: 'BOE MLED - Công nghệ Mini LED tiên tiến với độ sáng và độ tương phản cao.',
    category: 'Display',
    website: 'https://www.boe.com',
    products: [3, 4, 5, 6, 7],
  },
  {
    id: 3,
    name: 'Yellow River',
    slug: 'yellow-river',
    logo: '/images/brands/yellow-river.png',
    description: 'Yellow River - Thiết bị sân khấu chuyên nghiệp bao gồm Moving Head, Beam Light và Par LED.',
    category: 'Stage Equipment',
    website: 'https://www.yellowriver.com',
    products: [9],
  },
  {
    id: 4,
    name: 'MUXWAVE',
    slug: 'muxwave',
    logo: '/images/brands/muxwave.png',
    description: 'MUXWAVE chuyên cung cấp LED trong suốt (Transparent LED) với độ trong suốt cao.',
    category: 'Transparent LED',
    website: '',
    products: [],
  },
  {
    id: 5,
    name: 'GLOSHINE',
    slug: 'gloshine',
    logo: '/images/brands/gloshine.png',
    description: 'GLOSHINE - Giải pháp LED cho thuê (Rental) chất lượng cao cho sự kiện.',
    category: 'Rental LED',
    website: '',
    products: [],
  },
  {
    id: 6,
    name: 'PixelHue',
    slug: 'pixelhue',
    logo: '/images/brands/pixelhue.png',
    description: 'PixelHue - Bộ chuyển mạch video và console livestream chuyên nghiệp.',
    category: 'Processor',
    website: '',
    products: [],
  },
  {
    id: 7,
    name: 'G-Energy',
    slug: 'g-energy',
    logo: '/images/brands/g-energy.png',
    description: 'G-Energy - Nguồn LED chất lượng cao với hiệu suất và độ bền vượt trội.',
    category: 'Power Supply',
    website: '',
    products: [],
  },
  {
    id: 8,
    name: 'Ledman',
    slug: 'ledman',
    logo: '/images/brands/ledman.png',
    description: 'Ledman - LED Display với công nghệ COB tiên tiến.',
    category: 'Display',
    website: '',
    products: [],
  },
  {
    id: 9,
    name: 'FILMBASE',
    slug: 'filmbase',
    logo: '/images/brands/filmbase.png',
    description: 'FILMBASE - LED Film trong suốt dán kính với độ mỏng và độ trong suốt cao.',
    category: 'LED Film',
    website: '',
    products: [],
  },
  {
    id: 10,
    name: 'DJPOWER',
    slug: 'djpower',
    logo: '/images/brands/djpower.png',
    description: 'DJPOWER - Thiết bị hiệu ứng sân khấu bao gồm máy phun khói, pháo và quạt.',
    category: 'Stage Effects',
    website: '',
    products: [],
  },
  {
    id: 11,
    name: 'MAGNIMAGE',
    slug: 'magnimage',
    logo: '/images/brands/magnimage.png',
    description: 'MAGNIMAGE - Video Processor 4K/HDR chuyên nghiệp cho màn hình LED lớn.',
    category: 'Processor',
    website: '',
    products: [],
  },
];

export function getBrandBySlug(slug: string) {
  return BRANDS.find((b) => b.slug === slug);
}

export function getAllBrands() {
  return BRANDS;
}
